stages:
  data_ingestion:
    cmd: python scripts/data_ingestion.py
    deps:
      - scripts/data_ingestion.py
      - config/config.yaml
    outs:
      - data/raw:
          persist: true

  preprocess:
    cmd: python scripts/data_preprocessing.py --config config/config.yaml --visualize
    deps:
      - scripts/data_preprocessing.py
      - config/config.yaml
      - data/extracted/Task02_Heart/dataset.json
