stages:
  data_ingestion:
    cmd: python scripts/data_ingestion.py
    deps:
      - scripts/data_ingestion.py
      - config/config.yaml
    outs:
      - data/raw

  preprocess:
    cmd: python data_preprocessing.py
    deps:
      - data_preprocessing.py
      - config/config.yaml
      - data/extracted/Task02_Heart/dataset.json
    outs:
      - ./data (no-save)

