stages:
  data_ingestion:
    cmd: python scripts/data_ingestion.py
    deps:
      - scripts/data_ingestion.py
      - config/config.yaml
    outs:
      - data/raw:
          persist: true

  preprocess:
    cmd: python scripts/data_preprocessing.py --config config/config.yaml
    deps:
      - scripts/data_preprocessing.py
      - config/config.yaml
      - data/extracted/dataset.json

  train:
    cmd: python scripts/model_training.py
    deps:
      - scripts/model_training.py
      - scripts/data_preprocessing.py
      - scripts/model_loader.py
      - config/config.yaml

    metrics:
      - mlruns

  evaluate:
    cmd: python scripts/model_evaluation.py
    deps:
      - scripts/model_evaluation.py
      - scripts/data_preprocessing.py
      - scripts/model_loader.py
      - scripts/utils.py
      - config/config.yaml
