paths:
  raw_data: "data/raw"                # Directory for raw data
  extracted_data: "data/extracted"    # Directory for extracted tar files
  checkpoint: "checkpoints/best_model_heart.pth"
  results: "results/"

data_split:
  test_split: 0.1 
  val_split: 0.2

parameters:
  google_drive_link: "https://drive.google.com/uc?id=1wEB2I6S6tQBVEPxir8cA5kFB8gTQadYY"
  tar_file_name: "Task02_Heart.tar"        

training:
  learning_rate: 0.0001
  batch_size: 2
  num_epochs: 2
  weight_decay: 0.00001
  scheduler_step: 10
  scheduler_gamma: 0.5
  patience: 10


preprocessing:
  normalize: true  
  augmentation:
    flip: true  
    rotation: 15  # Max rotation angle in degrees (set 0 to disable)
  crop_dim: [128, 128, 64]  # Depth, Height, Width


logging:
  level: "info"  
  log_dir: "logs" 

output:
  model_dir: "models"  
  checkpoints: true 

mlflow:
  experiment_name: Heart Segmentation

model:
  name: UNet3D
  module: monai.networks.nets
  in_channels: 1
  out_channels: 2
  features: [16, 32, 64, 128, 256] 
  strides: [2, 2, 2, 2]
  dropout_rate_up: [0.1,0.1]
  dropout_rate_down: 0.1



