paths:
  raw_data: "data/raw"                # Directory for raw data
  extracted_data: "data/extracted/Task02_Heart"    # Directory for extracted tar files
  checkpoint: "checkpoints/best_model.pth"


parameters:
  google_drive_link: "https://drive.google.com/uc?id=1wEB2I6S6tQBVEPxir8cA5kFB8gTQadYY"
  tar_file_name: "Task02_Heart.tar"        # Name of the tar file after download

training:
  batch_size: 2  # Reduced batch size for 3D MRI volumes
  num_epochs: 10  # Increased epochs for sufficient training
  learning_rate: 0.0001  # Reduced learning rate for stable 3D data training

preprocessing:
  normalize: true  # Whether to normalize the images
  augmentation:
    flip: true  # Enable/disable flipping augmentation
    rotation: 15  # Max rotation angle in degrees (set 0 to disable)
  tile_height: 128  # Height of the cropped volume
  tile_width: 128  # Width of the cropped volume
  tile_depth: 64  # Depth of the cropped volume

logging:
  level: "info"  # Logging level: debug, info, warning, error
  log_dir: "logs"  # Directory for saving logs

output:
  model_dir: "models"  # Directory for saving trained models
  checkpoints: true  # Whether to save model checkpoints

mlflow:
  experiment_name: Heart Segmentation

model:
  name: UNet3D
  module: monai.networks.nets.UNet
  in_channels: 1
  out_channels: 2
  features: [16, 32, 64, 128, 256]  # Adjusted for 3D MRI segmentation
  strides: [2, 2, 2, 2]  # Progressive strides for down-sampling
